# Generated by Django 5.0.10 on 2026-06-24 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('total_points', models.IntegerField(default=0)),
                ('used_points', models.IntegerField(default=0)),
                ('remaining_points', models.IntegerField(default=0)),
                ('qr_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('card_pdf', models.FileField(blank=True, null=True, upload_to='loyalty_cards/pdf/')),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='loyalty_cards/images/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, null=True)),
                ('earned_points', models.IntegerField(default=0)),
                ('redeemed_points', models.IntegerField(default=0)),
                ('remaining_balance', models.IntegerField(default=0)),
                ('transaction_type', models.CharField(choices=[('EARN', 'Earn'), ('REDEEM', 'Redeem')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty_cards.loyaltycard')),
            ],
        ),
    ]
