# Generated by Django 5.0.10 on 2026-06-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltycard',
            name='first_card_popup_shown',
            field=models.BooleanField(default=False),
        ),
    ]
