# Generated by Django 5.0.10 on 2026-06-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_cards', '0002_loyaltycard_first_card_popup_shown'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltycard',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='loyalty_qr/'),
        ),
    ]
