# Generated by Django 5.0.10 on 2026-06-19 16:30

import uuid

from django.db import migrations, models


def populate_uuid_tokens(apps, schema_editor):
    Invoice = apps.get_model("users", "Invoice")
    KitchenOrder = apps.get_model("users", "KitchenOrder")

    for inv in Invoice.objects.filter(uuid_token__isnull=True):
        inv.uuid_token = uuid.uuid4().hex
        inv.save(update_fields=["uuid_token"])

    for ko in KitchenOrder.objects.filter(uuid_token__isnull=True):
        ko.uuid_token = uuid.uuid4().hex
        ko.save(update_fields=["uuid_token"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        # Step 1: add uuid_token as nullable (no unique yet)
        migrations.AddField(
            model_name="invoice",
            name="uuid_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="kitchenorder",
            name="uuid_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        # Step 2: populate existing rows
        migrations.RunPython(populate_uuid_tokens, migrations.RunPython.noop),
        # Step 3: make non-nullable and unique
        migrations.AlterField(
            model_name="invoice",
            name="uuid_token",
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="kitchenorder",
            name="uuid_token",
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        # Step 4: delete inventory models
        migrations.DeleteModel(
            name="InventoryIssue",
        ),
        migrations.DeleteModel(
            name="InventoryRequest",
        ),
    ]
