# Generated by Django 5.0.10 on 2026-06-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_inventory_removal'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='invoice_qrcodes/'),
        ),
    ]
