# Generated by Django 5.0.10 on 2026-06-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_invoice_payment_method_invoice_subtotal_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Asia/Karachi', max_length=100),
        ),
    ]
