# Generated by Django 5.0.10 on 2026-06-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
    ]
