# Generated by Django 5.0.10 on 2026-06-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_change_user_timezone_default_to_utc'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_loyalty_payment',
            field=models.BooleanField(default=False, help_text='Paid using loyalty points'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='loyalty_points_earned',
            field=models.IntegerField(default=0, help_text='Loyalty points earned from this order'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='loyalty_points_processed',
            field=models.BooleanField(default=False, help_text='Prevent duplicate point processing'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='loyalty_points_used',
            field=models.IntegerField(default=0, help_text='Loyalty points used for payment'),
        ),
    ]
