# Generated by Django 5.0.10 on 2026-06-25 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_invoice_is_loyalty_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('total_points', models.IntegerField(default=0)),
                ('used_points', models.IntegerField(default=0)),
                ('remaining_points', models.IntegerField(default=0)),
                ('qr_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='loyalty_qr/')),
                ('card_pdf', models.FileField(blank=True, null=True, upload_to='loyalty_cards/pdf/')),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='loyalty_cards/images/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=20)),
                ('first_card_popup_shown', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loyalty_cards_loyaltycard',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, null=True)),
                ('earned_points', models.IntegerField(default=0)),
                ('redeemed_points', models.IntegerField(default=0)),
                ('remaining_balance', models.IntegerField(default=0)),
                ('transaction_type', models.CharField(choices=[('EARN', 'Earn'), ('REDEEM', 'Redeem')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.loyaltycard')),
            ],
            options={
                'db_table': 'loyalty_cards_loyaltytransaction',
            },
        ),
    ]
