# Generated by Django 5.0.10 on 2026-06-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_create_loyalty_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRTableOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='qr_offer_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='QR Table Offer discount amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='qr_offer_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='QR Table Offer discount %', max_digits=5),
        ),
    ]
