# Generated by Django 5.0.10 on 2026-06-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_qrtableoffer_invoice_qr_offer_discount_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeBasedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='offer_banners/')),
                ('background_color', models.CharField(default='#f59e0b', max_length=20)),
                ('popup_image', models.ImageField(blank=True, null=True, upload_to='offer_popups/')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this offer has been applied')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TodayDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('deal_image', models.ImageField(blank=True, null=True, upload_to='deal_images/')),
                ('deal_banner', models.ImageField(blank=True, null=True, upload_to='deal_banners/')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
