# Generated by Django 5.0.10 on 2026-06-27 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_food_reward_points'),
        ('users', '0012_timebasedoffer_todaydeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='todaydeal',
            name='combo_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Special combo price for the deal', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='todaydeal',
            name='free_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_deals', to='menu.food'),
        ),
        migrations.AddField(
            model_name='todaydeal',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='deals', to='menu.food'),
        ),
    ]
