# Generated by Django 5.0.10 on 2026-06-27 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_todaydeal_combo_price_todaydeal_free_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='deal',
            field=models.ForeignKey(blank=True, help_text="Associated Today's Deal", null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.todaydeal'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deal_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Today's Deal discount amount", max_digits=10),
        ),
    ]
