# Generated by Django 5.0.10 on 2026-06-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_invoice_deal_invoice_deal_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='todaydeal',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage for percentage-based deals', max_digits=5, null=True),
        ),
    ]
