# Generated by Django 5.0.10 on 2026-06-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='reward_points',
            field=models.IntegerField(default=0, help_text='Points earned when customer orders this item'),
        ),
    ]
