# Generated by Django 5.0.10 on 2026-06-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_food_reward_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Mark as popular to show on homepage'),
        ),
    ]
